version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ai_advisor_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_advisor
    ports:
      - "5432:5432"
    volumes:
      - pgdata_ai_advisor:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ai_advisor"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata_ai_advisor:
